### ISSUE TITLE
char doesn't work pyopendds publishing message 

### ISSUE THREAD

**Issue by swolferDF** [Sdpierret/pyopendds#20]
I have a problem with char, not publish empty message. Same problem when i fill it
for exemple this idl : 
```
#ifndef INCLUDE_TEST
#define INCLUDE_TEST

module test {
    @topic
    struct messagechar {
        char data;
    };
};

#endif
```
I create python package : `pyidl test.idl -p Test`

exemple of code : 
```
from pytinydds import TinyDdsInputData,TinyDdsOutputData, TinyDdsQosType
from pyTest.test import messagechar


## main      
if __name__ == "__main__":
    _Dds= TinyDDS(43,discoveryConfig = TinyDdsDiscoveryConfig.TINYDDS_DISCOVERY_RTPS)
    topic_name = "publish char"
    sample = messagechar()
    print(sample)
    output = TinyDdsOutputData(topic_name,messagechar,_Dds,sample,qosType=TinyDdsQosType.TINYDDS_QOS_RELIABLE)
    output.publish()
    print("publish")
```
return error : 
```
messagechar(data='\x00')
Traceback (most recent call last):
  File "testchar.py", line 17, in <module>
    output.publish()
  File "/home/developer/Documents/env-python/lib/python3.8/site-packages/pytinydds/tinyddsData.py", line 129, in publish
    self._tinydds.pub(self._topicName,self._data,self._qosType)
  File "/home/developer/Documents/env-python/lib/python3.8/site-packages/pytinydds/tinydds.py", line 240, in 
pub
    rc = writer.write(data)
  File "/home/developer/Documents/env-python/lib/python3.8/site-packages/pyopendds/DataWriter.py", line 31, in write
    return self.topic.ts_package.write(self, sample)
ValueError: Error in getting obj.value
```

**Comment by swolferDF** [comment]
when I publish bytes it's ok 
see with @andrearuffino change    [ PrimitiveType.Kind.c8: ('str', "'\\x00'"),](https://github.com/Sdpierret/pyopendds/blob/master/pyopendds/dev/itl2py/PythonOutput.py#L25) by PrimitiveType.Kind.c8: ('Byte', 'Byte(0x00)'), but can cause some problem elsewhere
