### ISSUE TITLE
🐛 ImportError: libDFApplication_idl.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by swolferDF** [Sdpierret/pyopendds#33]
When I launch app with Application (pydragonflyApplication). I have this error : 
```
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    to1 = TestObj(app_name=appName1, domain_id=42)
  File "main.py", line 12, in __init__
    super().__init__(app_name, domain_id, *args, **kwargs)
  File "/home/developer/Documents/env3-20-python/lib/python3.8/site-packages/pydragonfly-0.1.0-py3.8.egg/dragonfly/application.py", line 123, in __init__
  File "/home/developer/Documents/env3-20-python/lib/python3.8/site-packages/pytinydds-0.2-py3.8.egg/pytinydds/tinyddsData.py", line 121, in __init__
  File "/home/developer/Documents/env3-20-python/lib/python3.8/site-packages/pytinydds-0.2-py3.8.egg/pytinydds/tinydds.py", line 194, in create_writer
  File "/home/developer/Documents/env3-20-python/lib/python3.8/site-packages/pyopendds/DomainParticipant.py", line 40, in create_topic
    return Topic(self, name, topic_type, qos, listener)
  File "/home/developer/Documents/env3-20-python/lib/python3.8/site-packages/pyopendds/Topic.py", line 27, in __init__
    self._ts_package: Any = importlib.import_module(
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/developer/Documents/env3-20-python/lib/python3.8/site-packages/_pyDFApplication/__init__.py", line 3, in <module>
    from ._pyDFApplication import *
ImportError: libDFApplication_idl.so: cannot open shared object file: No such file or directory
Exception ignored in: <function Application.__del__ at 0x7f6f00e8e550>
Traceback (most recent call last):
  File "/home/developer/Documents/env3-20-python/lib/python3.8/site-packages/pydragonfly-0.1.0-py3.8.egg/dragonfly/application.py", line 187, in __del__
AttributeError: 'TestObj' object has no attribute '_appHealthReport'
Exception ignored in: <function DomainParticipant.__del__ at 0x7f6f021e7d30>
Traceback (most recent call last):
  File "/home/developer/Documents/env3-20-python/lib/python3.8/site-packages/pyopendds/DomainParticipant.py", line 33, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
(7204|7204) WARNING: Service_Participant::~Service_Participant: There are 1 remaining domain participant(s). It is recommended to delete them before shutdown.
```

**Comment by Sdpierret** [comment]
I need more infos:
- what is the app
- how the app is built
- how the app is installed

**Comment by swolferDF** [comment]
For example when I launch the test :  /Platform/09-Tools/09-pyDragonflyApplication/tests/main.py
or GenericDdstoDds ... All app using Application

**Comment by swolferDF** [comment]
problem comes from cache sorry 😞

**Comment by swolferDF** [comment]
I have similar problem occur during packaging, and using service of generic Recorder. 
Using package https://github.com/Upnext-DragonFly/Platform/releases/tag/opendds-3.20 of DFApplication : 
error : 
```
mai 25 08:48:36 pc-platform polkitd(authority=local)[939]: Unregistered Authentication Agent for unix-process:14876:168061 (system bus name :1.201, object path /org/freedesktop/PolicyKit1/Authentication>
mai 25 08:48:36 pc-platform generic_recorder.py[14979]: Traceback (most recent call last):
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:   File "/usr/bin/generic_recorder.py", line 275, in <module>
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:     to1 = GenericRecorder(app_name=appName, idl_package=args.idl_package, config=args.configfile,
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:   File "/usr/bin/generic_recorder.py", line 155, in __init__
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:     super(GenericRecorder, self).__init__(app_name,
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:   File "/usr/lib/python3/dist-packages/dragonfly/application.py", line 123, in __init__
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:     self._appHealthReport = TinyDdsOutputData(HEALTH_REPORTS_TOPIC_NAME,AppReport,self._dds,qosType=TinyDdsQosType.TINYDDS_QOS_QUEUING)
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:   File "/usr/lib/python3/dist-packages/pytinydds/tinyddsData.py", line 121, in __init__
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:     self._tinydds.create_writer(self._topicName,self._topictype,self._qosType)
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:   File "/usr/lib/python3/dist-packages/pytinydds/tinydds.py", line 194, in create_writer
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:     topic = self.participant.create_topic(topic_name, topic_type)
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:   File "/usr/lib/python3/dist-packages/pyopendds/DomainParticipant.py", line 40, in create_topic
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:     return Topic(self, name, topic_type, qos, listener)
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:   File "/usr/lib/python3/dist-packages/pyopendds/Topic.py", line 27, in __init__
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:     self._ts_package: Any = importlib.import_module(
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:     return _bootstrap._gcd_import(name[level:], package, level)
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:   File "/usr/lib/python3/dist-packages/_pyDFApplication/__init__.py", line 3, in <module>
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:     from ._pyDFApplication import *
mai 25 08:48:36 pc-platform generic_recorder.py[14979]: ImportError: libDFApplication_idl.so: cannot open shared object file: No such file or directory
mai 25 08:48:36 pc-platform generic_recorder.py[14979]: Exception ignored in: <function Application.__del__ at 0x7efd7b82dee0>
mai 25 08:48:36 pc-platform generic_recorder.py[14979]: Traceback (most recent call last):
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:   File "/usr/lib/python3/dist-packages/dragonfly/application.py", line 187, in __del__
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:     self._appHealthReport._data.state = AppState.STOPPED
mai 25 08:48:36 pc-platform generic_recorder.py[14979]: AttributeError: 'GenericRecorder' object has no attribute '_appHealthReport'
mai 25 08:48:36 pc-platform generic_recorder.py[14979]: Exception ignored in: <function DomainParticipant.__del__ at 0x7efd7c9a45e0>
mai 25 08:48:36 pc-platform generic_recorder.py[14979]: Traceback (most recent call last):
mai 25 08:48:36 pc-platform generic_recorder.py[14979]:   File "/usr/lib/python3/dist-packages/pyopendds/DomainParticipant.py", line 33, in __del__
mai 25 08:48:36 pc-platform generic_recorder.py[14979]: ImportError: sys.meta_path is None, Python is likely shutting down
mai 25 08:48:36 pc-platform generic_recorder.py[14979]: (14979|14979) WARNING: Service_Participant::~Service_Participant: There are 1 remaining domain participant(s). It is recommended to delete them be>
mai 25 08:48:36 pc-platform systemd[1]: dragonfly-genericRecorder@Test.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by swolferDF** [comment]
Problem with **RPath** resolved :
in the environement python :` export KEEP_RPATH=true` before make pyidl
