### ISSUE TITLE
🐛 pyidl not working with genericImage.idl (octet sequence)

### ISSUE THREAD

**Issue by swolferDF** [Sdpierret/pyopendds#34]
I think the problem come from octet sequence
problem here : 
```
-- Generating done
-- Build files have been written to: /home/dragonfly/Documents/Dragonfly/Platform/10-Apps-IDL/01-DDS-IDL/build/pyidl-test42-build/build/test42/build/temp.linux-x86_64-cpython-38__pytest42
[1/2] Building CXX object CMakeFiles/_pytest42.dir/_pytest42.cpp.o
FAILED: CMakeFiles/_pytest42.dir/_pytest42.cpp.o 
/usr/bin/c++ -DOPENDDS_SECURITY -D__ACE_INLINE__ -D_pytest42_EXPORTS -I/home/dragonfly/Documents/env/lib/python3.8/site-packages/pyopendds-3.20-py3.8-linux-x86_64.egg/pyopendds/dev/include -isystem /usr/include/python3.8 -isystem /home/dragonfly/Documents/env/include -isystem /usr/include/orbsvcs -O3 -DNDEBUG -fPIC -pthread -std=gnu++14 -MD -MT CMakeFiles/_pytest42.dir/_pytest42.cpp.o -MF CMakeFiles/_pytest42.dir/_pytest42.cpp.o.d -o CMakeFiles/_pytest42.dir/_pytest42.cpp.o -c /home/dragonfly/Documents/Dragonfly/Platform/10-Apps-IDL/01-DDS-IDL/build/pyidl-test42-build/build/test42/_pytest42.cpp
/home/dragonfly/Documents/Dragonfly/Platform/10-Apps-IDL/01-DDS-IDL/build/pyidl-test42-build/build/test42/_pytest42.cpp: In static member function ‘static void pyopendds::Type<GenericCamera::StringSeq>::cpp_to_python(const GenericCamera::StringSeq&, PyObject*&)’:
/home/dragonfly/Documents/Dragonfly/Platform/10-Apps-IDL/01-DDS-IDL/build/pyidl-test42-build/build/test42/_pytest42.cpp:173:24: error: conversion from ‘TAO::unbounded_basic_string_sequence<char>::const_element_type’ {aka ‘TAO::details::string_const_sequence_element<TAO::details::string_traits<char, true> >’} to non-scalar type ‘pyopendds::s8’ {aka ‘TAO::String_Manager_T<char>’} requested
  173 |         s8 elem = cpp[i];
      |                        ^
/home/dragonfly/Documents/Dragonfly/Platform/10-Apps-IDL/01-DDS-IDL/build/pyidl-test42-build/build/test42/_pytest42.cpp:179:26: error: no matching function for call to ‘pyopendds::Type<TAO::String_Manager_T<char> >::cpp_to_python(pyopendds::s8&, PyObject*&)’
  179 |             , *field_elem);
      |                          ^
In file included from /home/dragonfly/Documents/env/lib/python3.8/site-packages/pyopendds-3.20-py3.8-linux-x86_64.egg/pyopendds/dev/include/pyopendds/user.hpp:5,
                 from /home/dragonfly/Documents/Dragonfly/Platform/10-Apps-IDL/01-DDS-IDL/build/pyidl-test42-build/build/test42/_pytest42.cpp:1:
/home/dragonfly/Documents/env/lib/python3.8/site-packages/pyopendds-3.20-py3.8-linux-x86_64.egg/pyopendds/dev/include/pyopendds/basictype.hpp:182:17: note: candidate: ‘static void pyopendds::StringType<T>::cpp_to_python(const T&, PyObject*&, const char*) [with T = TAO::String_Manager_T<char>; PyObject = _object]’
  182 |     static void cpp_to_python(const T& cpp, PyObject*& py, const char* encoding)
      |                 ^~~~~~~~~~~~~
/home/dragonfly/Documents/env/lib/python3.8/site-packages/pyopendds-3.20-py3.8-linux-x86_64.egg/pyopendds/dev/include/pyopendds/basictype.hpp:182:17: note:   candidate expects 3 arguments, 2 provided
/home/dragonfly/Documents/Dragonfly/Platform/10-Apps-IDL/01-DDS-IDL/build/pyidl-test42-build/build/test42/_pytest42.cpp: In static member function ‘static void pyopendds::Type<GenericCamera::StringSeq>::python_to_cpp(PyObject*, GenericCamera::StringSeq&)’:
/home/dragonfly/Documents/Dragonfly/Platform/10-Apps-IDL/01-DDS-IDL/build/pyidl-test42-build/build/test42/_pytest42.cpp:206:24: error: conversion from ‘TAO::unbounded_basic_string_sequence<char>::element_type’ {aka ‘TAO::details::string_sequence_element<TAO::details::string_traits<char, true> >’} to non-scalar type ‘pyopendds::s8’ {aka ‘TAO::String_Manager_T<char>’} requested
  206 |         s8 elem = cpp[i];
      |                        ^
/home/dragonfly/Documents/Dragonfly/Platform/10-Apps-IDL/01-DDS-IDL/build/pyidl-test42-build/build/test42/_pytest42.cpp:211:9: error: no matching function for call to ‘pyopendds::Type<TAO::String_Manager_T<char> >::python_to_cpp(PyObject*, pyopendds::s8&)’
  211 |         );
      |         ^
In file included from /home/dragonfly/Documents/env/lib/python3.8/site-packages/pyopendds-3.20-py3.8-linux-x86_64.egg/pyopendds/dev/include/pyopendds/user.hpp:5,
                 from /home/dragonfly/Documents/Dragonfly/Platform/10-Apps-IDL/01-DDS-IDL/build/pyidl-test42-build/build/test42/_pytest42.cpp:1:
/home/dragonfly/Documents/env/lib/python3.8/site-packages/pyopendds-3.20-py3.8-linux-x86_64.egg/pyopendds/dev/include/pyopendds/basictype.hpp:189:17: note: candidate: ‘static void pyopendds::StringType<T>::python_to_cpp(PyObject*, T&, const char*) [with T = TAO::String_Manager_T<char>; PyObject = _object]’
  189 |     static void python_to_cpp(PyObject* py, T& cpp, const char* encoding)
      |                 ^~~~~~~~~~~~~
/home/dragonfly/Documents/env/lib/python3.8/site-packages/pyopendds-3.20-py3.8-linux-x86_64.egg/pyopendds/dev/include/pyopendds/basictype.hpp:189:17: note:   candidate expects 3 arguments, 2 provided
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    setup(
  File "/home/dragonfly/Documents/env/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/dragonfly/Documents/env/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/home/dragonfly/Documents/env/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/home/dragonfly/Documents/env/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/home/dragonfly/Documents/env/lib/python3.8/site-packages/setuptools/dist.py", line 1229, in run_command
    super().run_command(command)
  File "/home/dragonfly/Documents/env/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/dragonfly/Documents/env/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/home/dragonfly/Documents/env/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/dragonfly/Documents/env/lib/python3.8/site-packages/setuptools/dist.py", line 1229, in run_command
    super().run_command(command)
  File "/home/dragonfly/Documents/env/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/dragonfly/Documents/env/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 136, in run
    self.run_command(cmd_name)
  File "/home/dragonfly/Documents/env/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/dragonfly/Documents/env/lib/python3.8/site-packages/setuptools/dist.py", line 1229, in run_command
    super().run_command(command)
  File "/home/dragonfly/Documents/env/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/dragonfly/Documents/env/lib/python3.8/site-packages/cmake_build_extension/build_extension.py", line 110, in run
    self.build_extension(ext)
  File "/home/dragonfly/Documents/env/lib/python3.8/site-packages/cmake_build_extension/build_extension.py", line 225, in build_extension
    subprocess.check_call(build_command)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '/home/dragonfly/Documents/Dragonfly/Platform/10-Apps-IDL/01-DDS-IDL/build/pyidl-test42-build/build/test42/build/temp.linux-x86_64-cpython-38__pytest42', '--config', 'Release']' returned non-zero exit status 1.

An error occured with the following command:
	CWD: /home/dragonfly/Documents/Dragonfly/Platform/10-Apps-IDL/01-DDS-IDL/build/pyidl-test42-build/build/test42
	CMD: python3 setup.py bdist_wheel --dist-dir=/home/dragonfly/Documents/Dragonfly/Platform/10-Apps-IDL/01-DDS-IDL/dist
Exiting pyidl with status 1.
```
idl here : 
```
#ifndef INCLUDE_GENERIC_IMAGE_IDL
#define INCLUDE_GENERIC_IMAGE_IDL

module GenericImage {

    enum ImageFormat {
        FORMAT_Y16,
        FORMAT_YUV422,
        FORMAT_MONO16,
        FORMAT_MONO8,
        FORMAT_BAYERRG8,
        FORMAT_BGR24,
        FORMAT_RGB24
    };

    enum CompressionType {
        NONE,
        BMP,
        JPEG,
        JP2,
        PNG,
        WEBP,
        PBM,
        PFM,
        SR,
        TIFF,
        EXR,
        HDR
    };


    struct NameValuePair {
        string name;
        string value;
    };

    typedef sequence<NameValuePair> NameValuePairSequence;

    typedef sequence<char> OctetSequence; 
    @topic

    struct Image {
        // Mandatory data
        string deviceRole;
        unsigned long frameId;
        OctetSequence data;
        long long timestamp_ns;
        long height;
        long width;
        long bitDepth;
        ImageFormat format;
        CompressionType encoding;

        // Additional specific data
        NameValuePairSequence additionalInformation;
    };
};

#endif
```
command launch : 
```
pyidl GenericImage.idl -p test42 --force-install -m'-j16'

**Comment by Sdpierret** [comment]
I just made the test:

``` bash
$ sudo apt install ./python3-cmake-build-extension_0.5.0_amd64.deb
[...]
$ sudo apt install ./python3-opendds_3.20-1_amd64.deb
[...]
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-Av3uEd/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 
$ cmake --version
cmake version 3.22.3
$ cd /tmp/
$ pyidl ~/DragonFly/GitHub/Platform/10-Apps-IDL/01-DDS-IDL/GenericImage.idl -p test42 
No virtual environment seems to be sourced. Would you like to continue ?y
-- The CXX compiler identification is GNU 9.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The C compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Could NOT find OpenSSL (missing: OpenSSL_DIR)
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1f")  
-- Could NOT find XercesC (missing: XercesC_DIR)
-- Found XercesC: /usr/lib/x86_64-linux-gnu/libxerces-c.so (found version "3.2.2") 
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/build/pyidl-test42-build/build
[ 14%] Generating opendds_generated/GenericImageTypeSupportImpl.h, opendds_generated/GenericImageTypeSupportImpl.cpp, opendds_generated/GenericImageTypeSupport.idl
[ 28%] Generating opendds_generated/GenericImageTypeSupportC.h, opendds_generated/GenericImageTypeSupportC.inl, opendds_generated/GenericImageTypeSupportS.h, opendds_generated/GenericImageTypeSupportC.cpp
[ 42%] Generating opendds_generated/GenericImageC.h, opendds_generated/GenericImageC.inl, opendds_generated/GenericImageS.h, opendds_generated/GenericImageC.cpp
[ 57%] Building CXX object CMakeFiles/test42_idl.dir/opendds_generated/GenericImageTypeSupportImpl.cpp.o
[ 71%] Building CXX object CMakeFiles/test42_idl.dir/opendds_generated/GenericImageC.cpp.o
[ 85%] Building CXX object CMakeFiles/test42_idl.dir/opendds_generated/GenericImageTypeSupportC.cpp.o
[100%] Linking CXX shared library libtest42_idl.so
[100%] Built target test42_idl
Install the project...
-- Install configuration: ""
-- Installing: prefix/usr/local/lib/libtest42_idl.so
-- Installing: prefix/usr/local/include/../../../home/dpierret/DragonFly/GitHub/Platform/10-Apps-IDL/01-DDS-IDL/GenericImage.idl
-- Installing: prefix/usr/local/include/test42_idl_export.h
-- Installing: prefix/usr/local/include/GenericImageTypeSupport.idl
-- Installing: prefix/usr/local/include/GenericImageTypeSupportImpl.h
-- Installing: prefix/usr/local/include/GenericImageC.h
-- Installing: prefix/usr/local/include/GenericImageC.inl
-- Installing: prefix/usr/local/include/GenericImageS.h
-- Installing: prefix/usr/local/include/GenericImageTypeSupportC.h
-- Installing: prefix/usr/local/include/GenericImageTypeSupportC.inl
-- Installing: prefix/usr/local/include/GenericImageTypeSupportS.h
-- Installing: prefix/usr/local/share/cmake/test42_idl/test42_idlTargets.cmake
-- Installing: prefix/usr/local/share/cmake/test42_idl/test42_idlTargets-noconfig.cmake
-- Installing: prefix/usr/local/share/cmake/test42_idl/test42_idlConfig.cmake
-- Installing: prefix/usr/local/lib/libTAO_PortableServer.so.2.2a_p23
-- Installing: prefix/usr/local/lib/libTAO_BiDirGIOP.so.2.2a_p23
-- Installing: prefix/usr/local/lib/libTAO_PI.so.2.2a_p23
-- Installing: prefix/usr/local/lib/libTAO_CodecFactory.so.2.2a_p23
-- Installing: prefix/usr/local/lib/libTAO_AnyTypeCode.so.2.2a_p23
-- Installing: prefix/usr/local/lib/libTAO.so.2.2a_p23
-- Installing: prefix/usr/local/lib/libACE.so.6.2a_p23
-- Installing: prefix/usr/local/lib/libOpenDDS_Dcps.so.3.20.0
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.8
creating build/lib.linux-x86_64-3.8/pytest42
copying pytest42/__init__.py -> build/lib.linux-x86_64-3.8/pytest42
creating build/lib.linux-x86_64-3.8/pytest42/GenericImage
copying pytest42/GenericImage/__init__.py -> build/lib.linux-x86_64-3.8/pytest42/GenericImage
running build_ext

==> Configuring:
$ cmake -S /tmp/build/pyidl-test42-build/build/test42 -B /tmp/build/pyidl-test42-build/build/test42/build/temp.linux-x86_64-3.8__pytest42 -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/tmp/build/pyidl-test42-build/build/test42/build/lib.linux-x86_64-3.8/_pytest42 -DPython3_ROOT_DIR=/usr -DCALL_FROM_SETUP_PY:BOOL=ON -DPYOPENDDS_INCLUDE=/usr/lib/python3/dist-packages/pyopendds/dev/include

==> Building:
$ cmake --build /tmp/build/pyidl-test42-build/build/test42/build/temp.linux-x86_64-3.8__pytest42 --config Release

==> Installing:
$ cmake --install /tmp/build/pyidl-test42-build/build/test42/build/temp.linux-x86_64-3.8__pytest42

-- The CXX compiler identification is GNU 9.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python3: /usr/include/python3.8 (found version "3.8.10") found components: Development Development.Module Development.Embed 
-- The C compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Could NOT find OpenSSL (missing: OpenSSL_DIR)
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1f")  
-- Could NOT find XercesC (missing: XercesC_DIR)
-- Found XercesC: /usr/lib/x86_64-linux-gnu/libxerces-c.so (found version "3.2.2") 
-- Configuring done
CMake Warning at /usr/local/lib/python3.8/dist-packages/cmake/data/share/cmake-3.22/Modules/FindPython/Support.cmake:3316 (add_library):
  Cannot generate a safe runtime search path for target _pytest42 because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libOpenDDS_Dcps.so.3.20.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /tmp/build/pyidl-test42-build/build/prefix/usr/local/lib
    runtime library [libTAO_PortableServer.so.2.2a_p23] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /tmp/build/pyidl-test42-build/build/prefix/usr/local/lib
    runtime library [libTAO_BiDirGIOP.so.2.2a_p23] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /tmp/build/pyidl-test42-build/build/prefix/usr/local/lib
    runtime library [libTAO_PI.so.2.2a_p23] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /tmp/build/pyidl-test42-build/build/prefix/usr/local/lib
    runtime library [libTAO_CodecFactory.so.2.2a_p23] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /tmp/build/pyidl-test42-build/build/prefix/usr/local/lib
    runtime library [libTAO_AnyTypeCode.so.2.2a_p23] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /tmp/build/pyidl-test42-build/build/prefix/usr/local/lib
    runtime library [libTAO.so.2.2a_p23] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /tmp/build/pyidl-test42-build/build/prefix/usr/local/lib
    runtime library [libACE.so.6.2a_p23] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /tmp/build/pyidl-test42-build/build/prefix/usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  /usr/local/lib/python3.8/dist-packages/cmake/data/share/cmake-3.22/Modules/FindPython3.cmake:494 (__Python3_add_library)
  CMakeLists.txt:11 (Python3_add_library)


-- Generating done
-- Build files have been written to: /tmp/build/pyidl-test42-build/build/test42/build/temp.linux-x86_64-3.8__pytest42
[2/2] Linking CXX shared module _pytest42.so
-- Install configuration: "Release"
-- Installing: /tmp/build/pyidl-test42-build/build/test42/build/lib.linux-x86_64-3.8/_pytest42/_pytest42.so
-- Set runtime path of "/tmp/build/pyidl-test42-build/build/test42/build/lib.linux-x86_64-3.8/_pytest42/_pytest42.so" to ""
/usr/local/lib/python3.8/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/_pytest42
copying build/lib.linux-x86_64-3.8/_pytest42/__init__.py -> build/bdist.linux-x86_64/wheel/_pytest42
copying build/lib.linux-x86_64-3.8/_pytest42/_pytest42.so -> build/bdist.linux-x86_64/wheel/_pytest42
creating build/bdist.linux-x86_64/wheel/pytest42
copying build/lib.linux-x86_64-3.8/pytest42/__init__.py -> build/bdist.linux-x86_64/wheel/pytest42
creating build/bdist.linux-x86_64/wheel/pytest42/GenericImage
copying build/lib.linux-x86_64-3.8/pytest42/GenericImage/__init__.py -> build/bdist.linux-x86_64/wheel/pytest42/GenericImage
running install_egg_info
running egg_info
creating pytest42.egg-info
writing pytest42.egg-info/PKG-INFO
writing dependency_links to pytest42.egg-info/dependency_links.txt
writing requirements to pytest42.egg-info/requires.txt
writing top-level names to pytest42.egg-info/top_level.txt
writing manifest file 'pytest42.egg-info/SOURCES.txt'
listing git files failed - pretending there aren't any
listing git files failed - pretending there aren't any
reading manifest file 'pytest42.egg-info/SOURCES.txt'
writing manifest file 'pytest42.egg-info/SOURCES.txt'
Copying pytest42.egg-info to build/bdist.linux-x86_64/wheel/pytest42-0.0.0-py3.8.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/pytest42-0.0.0.dist-info/WHEEL
creating '/tmp/dist/pytest42-0.0.0-cp38-cp38-linux_x86_64.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding '_pytest42/__init__.py'
adding '_pytest42/_pytest42.so'
adding 'pytest42/__init__.py'
adding 'pytest42/GenericImage/__init__.py'
adding 'pytest42-0.0.0.dist-info/METADATA'
adding 'pytest42-0.0.0.dist-info/WHEEL'
adding 'pytest42-0.0.0.dist-info/top_level.txt'
adding 'pytest42-0.0.0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
```

**Comment by p-e-s** [comment]
Now working
